spring:
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # 禁用缓存
    cache: false
    # thymeleaf非标准html
    servlet:
      content-type: text/html


  profiles:
    active: dev

  # 国际化配置文件（包名，基础名）
  messages:
    basename: i18n/messages,i18n/login


comment.avatar: /images/avatar.png

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.edu